import { StyleSheet, Platform } from 'react-native';

export const theme = {
  bg_primary:    '#0F0F17',
  bg_surface:    '#17181F',
  bg_card:       '#1F2030',
  accent:        '#FF6B6B',
  accent2:       '#4ECDC4',
  text_primary:  '#F0F0F5',
  text_secondary:'#8B8C9E',
  border:        '#2A2B3D',
};

const styles = StyleSheet.create({
  container_home: {
    flex: 1,
    backgroundColor: theme.bg_primary,
    paddingHorizontal: 24,
    paddingTop: 60,
    paddingBottom: 30,
    alignItems: 'center',
  },
  container_contato: {
    flex: 1,
    backgroundColor: theme.bg_primary,
    paddingHorizontal: 24,
    paddingTop: 20,
    alignItems: 'center',
  },
  container_icone_voltar_contato: {
    alignSelf: 'flex-start',
    marginTop: Platform.OS === 'ios' ? 10 : 20,
    padding: 8,
    backgroundColor: theme.bg_card,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: theme.border,
  },
  view_texto_contato: {
    marginVertical: 28,
    alignItems: 'center',
  },
  texto_contato: {
    fontSize: 26,
    fontWeight: 'bold',
    color: theme.text_primary,
    textAlign: 'center',
    letterSpacing: 0.3,
  },
  input_contato: {
    width: '100%',
    maxWidth: 440,
    height: 54,
    borderWidth: 1,
    borderColor: theme.border,
    borderRadius: 14,
    paddingHorizontal: 18,
    marginBottom: 14,
    backgroundColor: theme.bg_card,
    fontSize: 15,
    color: theme.text_primary,
  },
  inputArea: {
    width: '100%',
    maxWidth: 440,
    minHeight: 130,
    borderWidth: 1,
    borderColor: theme.border,
    borderRadius: 14,
    paddingHorizontal: 18,
    paddingTop: 14,
    marginBottom: 20,
    backgroundColor: theme.bg_card,
    textAlignVertical: 'top',
    fontSize: 15,
    color: theme.text_primary,
  },
  botao: {
    backgroundColor: theme.accent,
    paddingVertical: 16,
    borderRadius: 14,
    width: '100%',
    maxWidth: 340,
    alignItems: 'center',
    marginBottom: 14,
  },
  textoBotao: {
    color: '#fff',
    fontSize: 14,
    fontWeight: 'bold',
    letterSpacing: 1.2,
  },
});

export default styles;
